### ISSUE TITLE
Either I'm blind or it's no longer working

### ISSUE THREAD

**Issue by tjwoosta** [azrdev/firefox-cookie-whitelister#1]
I installed this Cookie Whitelist for fennec add-on a few weeks ago and I remember it was working great for a while, but now I can no longer seem to figure out how to add sites to the list. 

iirc there was a menu entry to add sites, but I can't find it. Either I'm blind or a recent Firefox update broke things

**Comment by azrdev** [comment]
Can confirm this on fennec 36, fixed in v0.9.4
