### ISSUE TITLE
Whitelisting permanent cookies not possible anymore

### ISSUE THREAD

**Issue by maffe** [azrdev/firefox-cookie-whitelister#2]
The button to allow permanent cookies is missing since a few weeks or months on my phone and tablet.
![screenshot_2015-10-24-15-22-12](https://cloud.githubusercontent.com/assets/515302/10711092/7ca39db0-7a71-11e5-80d6-44df2e3263e9.png)

**Comment by azrdev** [comment]
@maffe can you tell me your version of fennec and the addon?

**Comment by maffe** [comment]
@azrdev Firefox 41.0.2, addon version 0.9.4.

**Comment by comzeradd** [comment]
Same here on 41.

**Comment by azrdev** [comment]
I can confirm this, but cannot see why this is broken. Asking mozilla…

**Comment by azrdev** [comment]
Well, I finally found what broke us: See https://mail.mozilla.org/pipermail/mobile-firefox-dev/2015-June/001226.html and read carefully the [note for the `positive` parameter in doorhanger.show](https://developer.mozilla.org/en-US/Add-ons/Firefox_for_Android/API/NativeWindow/doorhanger#show%28%29)
