### ISSUE TITLE
Set appropriate permissions for Firefox Sync

### ISSUE THREAD

**Issue by maffe** [azrdev/firefox-cookie-whitelister#3]
When trying to set up Firefox Sync (about:accounts?action=signup), Firefox complains about missing Cookie and Local Storage permissions. After allowing cookies using this addon, the problem remains. It would be nice if the appropriate permissions could be set using this addon on the initial Sync page.

**Comment by maffe** [comment]
The permissions have to be set for `accounts.firefox.com`.

**Comment by azrdev** [comment]
Sorry, I don't get the problem. (a) When you disable cookies by default, sync breaks? This would be a sync issue. Or (b) when using sync, this addon breaks? Then I'd need to know a detailed error message, because the addon is not using cookies itself.

**Comment by maffe** [comment]
Sync needs cookie permissions for `accounts.firefox.com`. When trying to set it up, the URL in the location bar is `about:accounts?action=signup`. I just thought it would help users to set permissions for `accounts.firefox.com` when the user is at `about:accounts?action=signup`. But maybe this would lead to complicated code or unintended/obscure behaviour, feel free to close this issue.

**Comment by azrdev** [comment]
@maffe so it's (a) and has nothing to do with this addon. There is already a bug filed here, though: https://bugzilla.mozilla.org/show_bug.cgi?id=984098
